CLASS_NO = 0
CLASS_SM = 1
CLASS_MD = 2
CLASS_LG = 3

HEIGHT_NO = 63
HEIGHT_SM = 10
HEIGHT_MD = 20
HEIGHT_LG = 40

READINGS_PER_SAMPLE = 2000
TOTAL_EXPERIMENTS = 360
SAMPLING_RATE = 195

SENSOR_ACCURACY = 97.4
SENSOR_SD = 2.5
SENSOR_TESTED_DISTANCE_TRUE = 82
SENSOR_TESTED_OBSERVED_MODE = 80
SENSOR_TESTED_OBSERVED_AVERAGE = 80.45
SENSOR_TESTED_OBSERVED_MAX = 94
SENSOR_TESTED_OBSERVED_MIN = 45

ORIGINAL_DATASET_FILE_NAME = 'VI_mannual_test_dataset.csv'
DATA_SET_FOLDER = "./dataset"
RESULTS_FOLDER = "./results"